INSERT INTO ENTERTAINER(SEQ, ENT_NAME, ENT_INFO)
VALUES (1, '강호동', '통');
INSERT INTO ENTERTAINER(SEQ, ENT_NAME, ENT_INFO)
VALUES (2, '이상민', '음악의 신');
INSERT INTO ENTERTAINER(SEQ, ENT_NAME, ENT_INFO)
VALUES (3, '서장훈', '건물주');
INSERT INTO ENTERTAINER(SEQ, ENT_NAME, ENT_INFO)
VALUES (4, '김영철', '노잼');
INSERT INTO ENTERTAINER(SEQ, ENT_NAME, ENT_INFO)
VALUES (5, '이수근', '오락부장');
INSERT INTO ENTERTAINER(SEQ, ENT_NAME, ENT_INFO)
VALUES (6, '김희철', '돌I');
INSERT INTO ENTERTAINER(SEQ, ENT_NAME, ENT_INFO)
VALUES (7, '민경훈', '두성');