CREATE TABLE USER_INFO 
  ( 
     USER_ID       VARCHAR2(50) PRIMARY KEY, 
     USER_PW VARCHAR2(50)
  ); 

CREATE TABLE ENTERTAINER
  ( 
     SEQ        NUMBER(10, 0) PRIMARY KEY,
     ENT_NAME VARCHAR2(100), 
     ENT_INFO VARCHAR2(1000)
  ); 